### PR TITLE
OpenLayers 6 and ES6

### PR DESCRIPTION
**Pull request by billingb**
Add ES6 support and an OpenLayers 6 canvas. Based on Atlascine branch.

### CODE REVIEW

**Comment by billingb** [comment]
I've been unable to figure out so far how css is supposed to be added in the ES6 code, I'll be looking at if I can figure that out to move the css file I added. Any ideas?

**Comment by billingb** [comment]
> 
> 
> I've been unable to figure out so far how css is supposed to be added in the ES6 code, I'll be looking at if I can figure that out to move the css file I added. Any ideas?

I've resolved the issue and moved the css to the es6 folder.

**Comment by billingb** [comment]
@ahayes @alexgao1 I've moved the WMS legend rendering into the legend widget and also enhanced the OL6 canvas to work with the legend widget (it didn't dispatch style info previously). Please look at the revised merge request and let me know what you think.

**Comment by ahayes** [comment]
How are you feeling about this branch these days? Safe to merge into master?

**Comment by billingb** [comment]
I'm using this branch in production for the Yupik atlas and a new atlas at NSIDC. I'm happy merging, it is really up to you and Alex.

**Review by alexgao1 — APPROVED** [review]
The starting Atlascine code contains a fair amount of problems, minor and major. Most of the commented out test code or TODO notes have been removed so that some semblance of cleaner code is merged into master. Merging this code in allows one to use an OL6 map, although it's not sure whether or not all of the functionality is complete as expected. The documentation to use it in canvas.json is also unclear and would need to be derived from the understanding of the map code and/or Atlascine canvas.json files already in use.

**Comment by ahayes** [comment]
OK thanks @alexgao1
@billingb Can you please add some Atlas Builder documentation for what is currently possible with the ol6 canvas type and wms legend? Maybe include a note about it being experimental and not initially supporting all the features of map, such as editing?

**Pull request merged**
