### PR TITLE
Feature: Filterable Legend Widget

### PR DESCRIPTION
**Pull request by alexgao1**

### CODE REVIEW

**Comment by alexgao1** [comment]
(documentation draft)  
The filterable legend widget allows for model filtering control within a legend for a map canvas.  
A sample configuration follows:  
```
{
	"widgetType": "filterableLegendWidgetWithGraphic",
	"name": "My Filterable Legend Widget",
	"containerId": "htmlElementId",
	"sourceModelId": "myFilteringModel",
	"designatedCanvasName": "My Map",
	"allLabel": "All Selections",
	"graphicType": "none"
}
```
* **widgetType**: A string. It must be "filterableLegendWidgetWithGraphic" for the default behaviour.
* **name**: A string.
* **containerId**: A string. The "id" of an HTML element on the page that this element should start rendering in reference to.
* **sourceModelId**: A string. The "modelId" of the model that is providing documents to the filterable legend widget. This model should be a filter model. This will also be the source of documents for the state of the graphic to draw from, if the widget is specified to have a graphic.
* **designatedCanvasName**: A string. This is the name of the corresponding canvas that this widget will be drawn on.
* **allLabel**: A string. The name of the label that toggles all entries in the legend widget on or off.
* **graphicType**: A string.
    * "none", for no graphic to appear beside the legend
    * "custom", where the user must override/extend the existing widget and define behaviour for drawing the graphic themselves
        * The function `drawCustom` must be implemented
    * "pie", **which is not implemented at this time**
  
If graphicType is not "none", then `prepareGraphicData` must be implemented.  
  
Advanced: The filterable legend widget contains a property `this.preloadCallback`, which is available to receive a function reference to load in data before loading in other data/graphics.

**Review by billingb — DISMISSED** [review]

**Review by billingb — DISMISSED** [review]

**Comment by ahayes** [comment]
Do we create a default container if a containerId is not provided?

Can you explain the flow and sourceModelId vs sourceCanvasName?

Is the graphicType referring to the new extra stuff that it is possible to attach beside the legend (like the graphing timeline?)

**Comment by alexgao1** [comment]
### Do we create a default container if a containerId is not provided?

No. This behaviour is consistent with the other LegendWidgets that throw an error if `containerId` is not provided.

### Can you explain [...] sourceModelId vs sourceCanvasName?

`sourceModelId` is the filter model that will allow the user to make selections on to filter things. `sourceCanvasName` is the name of the canvas that this legend widget will be associated with and will be receiving styles from.

### Is the graphicType referring to the new extra stuff that it is possible to attach beside the legend (like the graphing timeline?)

Yes. There are only "none" or "custom" options, where custom will have to be provided by the user.


### Can you explain the flow [...]?

The widget is created. The dispatcher setup events are performed as needed. The legend and graphic (if set to do so) are drawn. The legend and graphic will be redrawn/updated on various dispatch handlers pertaining to the original filter model `sourceModelId` and the canvas reporting its styles.  

(Click the top right <-> to expand the diagram)

```mermaid
graph TD;
subgraph Widget Creation
  1[Widget is created, initial dispatcher setup] --> 2[Draw method];
  2[Draw method] --> 3[Draw legend];
  2[Draw method] -- if graphicType is not none --> 4[Draw graphic];
  4[Draw graphic] -- if graphicType is custom --> 5[Draw custom];
end
subgraph Dispatch Handlers
6[Model change available choices event] --> 3[Draw legend];
6[Model change available choices event] -- if graphicType is not none --> 4[Draw graphic];
7[Model change selection event] --> 11[Adjust selected items in legend];
8[Model change all selection event] --> 11[Adjust selected items in legend];
9[Model state updated event] --> 12[Source model updated];
12[Source model updated] -- if graphicType is not none --> 4[Draw graphic];
10[Canvas style report event] --> 3[Draw legend];
end
```

**Review by ahayes — APPROVED** [review]
Thanks, @alexgao1 and @billingb
I look forward to trying it out!

**Pull request merged**
