### PR TITLE
ES6 N2MapCanvas clean

### PR DESCRIPTION
**Pull request by alexgao1**

### CODE REVIEW

**Review by billingb — DISMISSED** [review]
much better!

**Comment by alexgao1** [comment]
At this point, the n2es6 files **build** again. The code is all untested in terms of whether or not it successfully runs within Nunaliit. Needs testing.

**Comment by alexgao1** [comment]
related to #998  
npm audit reports (3 low, 6 high, 2 critical) vulnerabilities  
gulp-cssmin is unmaintained, gulp-util is deprecated (needed to be installed to move to newer version of npm/node)

**Comment by alexgao1** [comment]
Previous npm and node versions:  
```
node --version
v11.15.0

npm --version
6.7.0
```  

Current versions:  
```
node --version
v16.14.2

npm --version
8.5.0
```

**Review by billingb — APPROVED** [review]

**Pull request merged**
